# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
builds:
  -
    skip: true
release:
  github:
    owner: yogendra0sharma
    name: mendix-privatecloud-go-sdk

  draft: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true